name: Отчет о дефекте
description: Шаблон-форма отчета о дефекте
title: "[Bug]: "
labels: ["bug"]
assignees:
  - netkitgit
body:
  - type: markdown
    attributes:
      value: |
        Заголовок заполняется по формуле "ЧТО. ГДЕ. КОГДА.". По-возможности заполните все поля
  - type: textarea
    id: bug-description
    attributes:
      label: Описание дефекта
      description: Подготовьте скриншоты и фрагменты лога заранее. Для описания дефекта воспользуйтесь указанным ниже шаблоном.
      value: "**Стенд**

              * Название стенда


              **Версия ПО**

              * Версия SUT


              **Предусловие:**

              * Описание предусловия

              * Описание предусловия


              **Шаги:**

              # Шаг №1

              # Шаг №2


              **Ожидаемый результат:**

              * Описание ОР


              **Фактический результат:**

              * Описание ФР"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Фрагмент лога (если есть)
      description: Здесь только фрагмент лога, с указанием ошибки или других событий, которые помогут программисту.
      render: shell
